from config import ADMIN_USERNAME

FALLBACK = {
    'bienvenida': (
        "{user} 🇨🇱 ¡Bienvenido a DriveVIPclub! 🇨🇱\n\n"
        "El Drive de contenido (+18) con ya +1500 perfiles, +{tamano} y +{videos} videos + {fotos} fotos en contenido 📦\n\n"
        "⚠️ Recuerda:\n\n"
        "✅ Lee mensajes fijados para tener toda la info 📌\n\n"
        "✅ Mira la lista de modelos en el Drive para saber cuáles tenemos\n\n"
        "✅ Se acepta todo medio de pago y tu compra es safe 🔒\n\n"
        "✅ Soporte y consultas escribe un DM ✉️\n\n"
        "Este mensaje se borrará en minutos para mantener chat limpio.\n\n"
        "{admin}"
    ),
    'precios': (
        "💎 MENÚ VIP - DRIVEVIPCLUB 💎\n\n"
        "🔥 LOS MEJORES PRECIOS DE CHILE 🔥\n\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "💎 PLAN SEMANAL - $4.990\n"
        "   • 7 días de acceso ilimitado\n"
        "   • Ideal para conocer el drive\n\n"
        "💎 PLAN MENSUAL - $8.990 ⭐ MÁS VENDIDO\n"
        "   • 30 días de acceso total\n"
        "   • Actualizaciones semanales\n"
        "━━━━━━━━━━━━━━━━━━━━\n\n"
        "💳 PAGO SEGURO CON MERCADOPAGO:\n\n"
        "🔹 Pagar Semanal ($4.990):\n"
        " https://mpago.la/19ATBAT\n\n"
        "🔹 Pagar Mensual ($8.990):\n"
        " https://mpago.la/1UZKTc8\n\n"
        "📲 PROCESO SIMPLE:\n"
        "1️⃣ Click en el link de tu plan\n"
        "2️⃣ Acredita tu pago (acepta todas las tarjetas)\n"
        "3️⃣ Envía comprobante a {admin}\n"
        "4️⃣ Recibe acceso inmediato a tu email\n\n"
        "⚡ Tiempo promedio: 5-15 minutos\n"
        "🔒 100% seguro y confidencial\n"
        "✅ Acepta débito, crédito y prepago\n\n"
        "📞 ¿Dudas? Escríbele a {admin}"
    ),
    'contenido': (
        "📦 CONTENIDO EXCLUSIVO DRIVEVIPCLUB\n\n"
        "🌟 LO QUE OBTIENES:\n\n"
        "✅ +{carpetas} CARPETAS ORGANIZADAS\n"
        "   • Contenido actualizado SEMANALMENTE\n"
        "   • Categorías fáciles de navegar\n\n"
        "✅ +{tamano} DE CONTENIDO PREMIUM\n"
        "   • Solo material verificado y de calidad\n"
        "   • Resoluciones HD disponibles\n\n"
        "✅ +{videos} VIDEOS + {fotos} FOTOS DISPONIBLES\n"
        "   • Creadores chilenos e internacionales\n"
        "   • Iremos agregando más fuentes\n\n"
        "✅ ACCESO INMEDIATO\n"
        "   • Recibes el drive en tu Gmail\n"
        "   • Acceso desde cualquier dispositivo\n\n"
        "📋 LISTA COMPLETA DE CONTENIDO:\n"
        "https://tinyurl.com/273anthz\n\n"
        "📊 REVISA LA PLANILLA PARA MÁS DETALLE:\n"
        "   • Total de videos: {videos}\n"
        "   • Total de fotos: {fotos}\n"
        "   • Peso total: {tamano}\n\n"
        "📂 CATEGORÍAS DISPONIBLES:\n"
        "• Creadores chilenos 🇨🇱\n"
        "• Creadores latinos 🌎\n"
        "• Internacionales 🌍\n\n"
        "💬 Para comprar: {admin}\n"
        "💰 Links de pago en /precios"
    ),
    'contacto': (
        "📞 CONTACTO DIRECTO - {admin}\n\n"
        "💬 SOPORTE Y CONSULTAS\n\n"
        "👤 Tu admin: {admin}\n\n"
        "✨ ESCRÍBEME PARA:\n"
        "✅ Consultas sobre el servicio\n"
        "✅ Ayuda con tu compra\n"
        "✅ Soporte post-venta\n"
        "✅ Renovar tu membresía\n"
        "✅ Dudas sobre el contenido disponible\n\n"
        "⏰ ATENCIÓN 24/7 — Responde al instante\n\n"
        "📲 CÓMO CONTACTAR:\n"
        "1. Click en {admin}\n"
        "2. Inicia conversación\n"
        "3. Cuéntame qué necesitas\n\n"
        "🔒 Tu información es 100% confidencial\n"
        "⚡ Respuesta rápida garantizada\n\n"
        "💬 Mensaje sugerido:\n"
        "\"Hola! Compré una membresía y necesito acceso\""
    ),
    'auto_00': (
        "🌙 ÚLTIMO AVISO DEL DÍA\n\n"
        "El canal queda disponible y mañana seguimos con novedades.\n"
        "📦 El Drive recibe material nuevo todas las semanas.\n\n"
        "💎 Revisa planes: /precios | 📂 Contenido: /contenido"
    ),
    'auto_08': (
        "👀 SEGUIMOS ATENDIENDO CON NORMALIDAD\n\n"
        "📋 En el listado puedes ver por perfil la cantidad de videos, fotos y tamaño disponible.\n"
        "📦 Seguimos subiendo material nuevo, por eso el catálogo crece cada semana.\n\n"
        "⚡ Contacto: {admin}\n"
        "📌 Referencias: https://t.me/drivechileno1\n\n"
        "💎 Planes: /precios | 📂 Contenido: /contenido"
    ),
    'auto_12': (
        "🔥 CONTENIDO EN ALTA CALIDAD\n\n"
        "🎬 Videos premium, resoluciones HD y perfiles organizados para encontrar contenido rápido.\n"
        "📋 Revisa el listado para conocer el peso y cantidad de videos de cada perfil.\n\n"
        "⚡ Contacto: {admin}\n"
        "💎 Acceso: /precios | 📂 Catálogo: /contenido"
    ),
    'auto_16': (
        "📦 EL DRIVE SIGUE CRECIENDO\n\n"
        "Cada semana añadimos material. Algunos perfiles todavía tienen contenido pendiente por subir.\n"
        "🎬 Revisa el listado para ver qué ya está disponible y su tamaño actual.\n\n"
        "⚡ Contacto: {admin}\n"
        "📌 Referencias: https://t.me/drivechileno1\n\n"
        "💎 Ver planes: /precios"
    ),
    'auto_20': (
        "⚡ ACCESO A CONTENIDO PREMIUM\n\n"
        "Videos de alta calidad, contenido exclusivo y actualizaciones constantes en el Drive.\n"
        "📋 El listado muestra el detalle de cada perfil para que sepas qué encontrarás.\n\n"
        "⚡ Pago por Mercado Pago o transferencias coordinadas por DM: {admin}\n"
        "💎 Planes: /precios | 📂 Contenido: /contenido"
    ),
}
