from config import ADMIN_USERNAME

FALLBACK = {
    'bienvenida': (
        "{user} 🇨🇱 ¡Bienvenido a DriveVIPclub! 🇨🇱\n\n"
        "El Drive de contenido (+18) con ya +1500 perfiles, +{tamano} y +{videos} videos + {fotos} fotos en contenido 📦\n\n"
        "⚠️ Recuerda:\n\n"
        "✅ Lee mensajes fijados para tener toda la info 📌\n\n"
        "✅ Mira la lista de modelos en el Drive para saber cuáles tenemos\n\n"
        "✅ Se acepta todo medio de pago y tu compra es safe 🔒\n\n"
        "✅ Soporte y consultas escribe un DM ✉️\n\n"
        "Este mensaje se borrará en minutos para mantener chat limpio.\n\n"
        "{admin}"
    ),
    'precios': (
        "💎 MENÚ VIP - DRIVEVIPCLUB 💎\n\n"
        "🔥 LOS MEJORES PRECIOS DE CHILE 🔥\n\n"
        "━━━━━━━━━━━━━━━━━━━━\n"
        "💎 PLAN SEMANAL - $4.990\n"
        "   • 7 días de acceso ilimitado\n"
        "   • Ideal para conocer el drive\n\n"
        "💎 PLAN MENSUAL - $8.990 ⭐ MÁS VENDIDO\n"
        "   • 30 días de acceso total\n"
        "   • Actualizaciones semanales\n"
        "━━━━━━━━━━━━━━━━━━━━\n\n"
        "💳 PAGO SEGURO CON MERCADOPAGO:\n\n"
        "🔹 Pagar Semanal ($4.990):\n"
        " https://mpago.la/19ATBAT\n\n"
        "🔹 Pagar Mensual ($8.990):\n"
        " https://mpago.la/1UZKTc8\n\n"
        "📲 PROCESO SIMPLE:\n"
        "1️⃣ Click en el link de tu plan\n"
        "2️⃣ Acredita tu pago (acepta todas las tarjetas)\n"
        "3️⃣ Envía comprobante a {admin}\n"
        "4️⃣ Recibe acceso inmediato a tu email\n\n"
        "⚡ Tiempo promedio: 5-15 minutos\n"
        "🔒 100% seguro y confidencial\n"
        "✅ Acepta débito, crédito y prepago\n\n"
        "📞 ¿Dudas? Escríbele a {admin}"
    ),
    'contenido': (
        "📦 CONTENIDO EXCLUSIVO DRIVEVIPCLUB\n\n"
        "🌟 LO QUE OBTIENES:\n\n"
        "✅ +{carpetas} CARPETAS ORGANIZADAS\n"
        "   • Contenido actualizado SEMANALMENTE\n"
        "   • Categorías fáciles de navegar\n\n"
        "✅ +{tamano} DE CONTENIDO PREMIUM\n"
        "   • Solo material verificado y de calidad\n"
        "   • Resoluciones HD disponibles\n\n"
        "✅ +{videos} VIDEOS + {fotos} FOTOS DISPONIBLES\n"
        "   • Creadores chilenos e internacionales\n"
        "   • Iremos agregando más fuentes\n\n"
        "✅ ACCESO INMEDIATO\n"
        "   • Recibes el drive en tu Gmail\n"
        "   • Acceso desde cualquier dispositivo\n\n"
        "📋 LISTA COMPLETA DE CONTENIDO:\n"
        "https://tinyurl.com/273anthz\n\n"
        "📊 REVISA LA PLANILLA PARA MÁS DETALLE:\n"
        "   • Total de videos: {videos}\n"
        "   • Total de fotos: {fotos}\n"
        "   • Peso total: {tamano}\n\n"
        "📂 CATEGORÍAS DISPONIBLES:\n"
        "• Creadores chilenos 🇨🇱\n"
        "• Creadores latinos 🌎\n"
        "• Internacionales 🌍\n\n"
        "💬 Para comprar: {admin}\n"
        "💰 Links de pago en /precios"
    ),
    'contacto': (
        "📞 CONTACTO DIRECTO - {admin}\n\n"
        "💬 SOPORTE Y CONSULTAS\n\n"
        "👤 Tu admin: {admin}\n\n"
        "✨ ESCRÍBEME PARA:\n"
        "✅ Consultas sobre el servicio\n"
        "✅ Ayuda con tu compra\n"
        "✅ Soporte post-venta\n"
        "✅ Renovar tu membresía\n"
        "✅ Dudas sobre el contenido disponible\n\n"
        "⏰ ATENCIÓN 24/7 — Responde al instante\n\n"
        "📲 CÓMO CONTACTAR:\n"
        "1. Click en {admin}\n"
        "2. Inicia conversación\n"
        "3. Cuéntame qué necesitas\n\n"
        "🔒 Tu información es 100% confidencial\n"
        "⚡ Respuesta rápida garantizada\n\n"
        "💬 Mensaje sugerido:\n"
        "\"Hola! Compré una membresía y necesito acceso\""
    ),
    'auto_4h': (
        "👀 SEGUIMOS ATENDIENDO CON NORMALIDAD\n\n"
        "⚡ Se acepta pago por Mercado Pago y transferencias coordinadas por DM.\n"
        "⚡ Contacto: {admin}\n"
        "⚡ Si no puedes enviar DM, reacciona a este mensaje y el bot te indicará cómo continuar.\n\n"
        "📌 Canal de referencias: https://t.me/drivechileno1\n"
        "📦 Contenido nuevo añadido al Drive todas las semanas.\n\n"
        "💎 Ver planes: /precios | 📂 Ver contenido: /contenido"
    ),
    'auto_noche': (
        "🌙 BUENAS NOCHES — SIGUE DISPONIBLE 🌙\n\n"
        "Seguimos atendiendo y el Drive sigue disponible.\n\n"
        "⚡ Pago por Mercado Pago o transferencias coordinadas por DM.\n"
        "⚡ Contacto: {admin}\n"
        "📌 Referencias: https://t.me/drivechileno1\n\n"
        "💎 Ver planes: /precios | 📂 Ver contenido: /contenido"
    ),
    'auto_finde': (
        "🎉 ¡FIN DE SEMANA DRIVEVIPCLUB! 🎉\n\n"
        "El Drive se actualiza todas las semanas con contenido nuevo.\n\n"
        "⚡ Pago por Mercado Pago o transferencias coordinadas por DM.\n"
        "⚡ Contacto: {admin}\n"
        "📌 Referencias: https://t.me/drivechileno1\n\n"
        "💎 Ver planes: /precios | 📂 Ver contenido: /contenido"
    ),
    'offline': (
        "😴 El bot está offline\n\n"
        "Horario de atención: 08:00 - 22:00 (Hora Chile)\n\n"
        "Vuelve en horario hábil o escribe a {admin}\n\n"
        "¡Gracias por entender! 🙌"
    ),
}
