from config import ADMIN_USERNAME

FALLBACK = {
    'bienvenida': (
        "{user} 🇨🇱 ¡Bienvenido a DriveVIPclub!\n\n"
        "📂 {carpetas} modelos organizados de la A a la Z\n"
        "🎬 {videos} videos\n"
        "📸 {fotos} fotos\n"
        "🔄 Actualizaciones todas las semanas\n"
        "💾 Descargas sin límites\n\n"
        "📌 Revisa los mensajes fijados:\n"
        "• Estructura real del Drive\n"
        "• Listado completo del contenido\n\n"
        "💎 Planes desde $4.990\n"
        "💳 Aceptamos pagos nacionales: MercadoPago (débito, crédito y transferencia)\n"
        "🌍 Aceptamos pagos del extranjero: PayPal\n\n"
        "🤖 Suscríbete con @DriveVIPclubBot\n"
        "💬 Atención directa: {admin}\n\n"
        "Este mensaje se eliminará en 15 minutos."
    ),
    'precios': (
        "💎 CÓMO SUSCRIBIRTE A DRIVEVIPCLUB\n\n"
        "🇨🇱 PAGO EN CHILE — MERCADOPAGO\n"
        "PLAN SEMANAL — $4.990 CLP\n"
        "✅ 7 días de acceso completo\n\n"
        "PLAN MENSUAL — $8.990 CLP ⭐\n"
        "✅ 30 días de acceso completo\n"
        "✅ Actualizaciones semanales incluidas\n\n"
        "💳 Acepta: débito, crédito, prepago y TRANSFERENCIA bancaria\n"
        "🤖 Usa /semanal o /mensual en el bot\n\n"
        "🌍 PAGO DESDE EL EXTRANJERO — PAYPAL\n"
        "PLAN MENSUAL — $10 USD ⭐\n"
        "✅ 30 días de acceso completo\n"
        "✅ Pago seguro con PayPal\n\n"
        "🤖 Usa /paypal en el bot para obtener el link\n\n"
        "📋 Antes de pagar, revisa el contenido con /lista.\n"
        "💬 ¿Dudas? Habla con {admin}"
    ),
    'contenido': (
        "📦 CONTENIDO EXCLUSIVO DRIVEVIPCLUB\n\n"
        "🌟 LO QUE NOS DIFERENCIA:\n\n"
        "✅ TRANSPARENCIA TOTAL\n"
        "   • Planilla detallada con videos/fotos por modelo\n"
        "   • Sabes EXACTAMENTE qué recibes antes de pagar\n"
        "   • /lista - Ver planilla completa\n\n"
        "✅ ORGANIZACIÓN IMPECABLE\n"
        "   • Carpetas ordenadas ALFABÉTICAMENTE (A-Z)\n"
        "   • Encuentra rápido lo que buscas\n"
        "   • Sin contenido desordenado\n\n"
        "✅ CALIDAD Y CANTIDAD\n"
        "   • {carpetas} modelos disponibles\n"
        "   • {videos} VIDEOS de alta calidad\n"
        "   • {fotos} fotos organizadas por carpeta\n"
        "   • {tamano} de contenido\n"
        "   • Resoluciones HD\n"
        "   • 📡 Datos actualizados desde nuestra planilla\n\n"
        "✅ ACTUALIZACIONES CONSTANTES\n"
        "   • Material nuevo TODAS LAS SEMANAS\n"
        "   • Sin costo adicional\n"
        "   • Siempre hay contenido fresco\n\n"
        "✅ ACCESO SIN LÍMITES\n"
        "   • Descarga TODO lo que quieras\n"
        "   • Sin restricciones de cantidad\n"
        "   • Acceso 24/7 desde cualquier dispositivo\n\n"
        "📋 LISTA COMPLETA DE CONTENIDO:\n"
        "https://docs.google.com/spreadsheets/d/1K5lJLdMJfPH76JrV4uC9-QdDly8rLg8XAWxoecWAe3k/edit\n\n"
        "📂 CATEGORÍAS:\n"
        "• Creadores chilenos 🇨🇱\n"
        "• Creadores latinos 🌎\n"
        "• Internacionales 🌍\n\n"
        "🤖 Para comprar: @DriveVIPclubBot\n"
        "🛠️ Ayuda después del pago: {admin}\n"
        "💰 Links de pago: /precios\n\n"
        "🔥 ¡El drive más ordenado y transparente de Chile!"
    ),
    'contacto': (
        "🤖 SOPORTE Y VENTAS\n\n"
        "Escríbele a @DriveVIPclubBot para:\n"
        "✅ Revisar planes con /precios\n"
        "✅ Consultar el contenido con /lista\n"
        "✅ Comprar con /semanal, /mensual o /paypal\n"
        "✅ Activar o renovar tu membresía\n\n"
        "🛠️ ¿Ya pagaste y necesitas ayuda?\n"
        "Contacta a {admin} e indica tu usuario, plan y Gmail.\n\n"
        "💡 Revisa /lista antes de comprar para conocer el contenido disponible."
    ),
    'lista': (
        "📂 LISTADO COMPLETO DEL DRIVE\n\n"
        "Consulta exactamente qué contenido está disponible antes de pagar.\n\n"
        "📊 RESUMEN ACTUALIZADO\n"
        "• {carpetas} modelos organizados de la A a la Z\n"
        "• {videos} videos\n"
        "• {fotos} fotos\n"
        "• {tamano} de contenido\n\n"
        "En la planilla encontrarás el nombre de cada creadora y la cantidad de videos y fotos de su carpeta.\n\n"
        "🔎 CÓMO REVISARLA\n"
        "1. Abre el enlace\n"
        "2. Busca la creadora por orden alfabético\n"
        "3. Revisa sus cantidades de videos y fotos\n\n"
        "📋 LISTADO PÚBLICO:\n"
        "https://docs.google.com/spreadsheets/d/1K5lJLdMJfPH76JrV4uC9-QdDly8rLg8XAWxoecWAe3k/edit?gid=0#gid=0\n\n"
        "🤖 Suscríbete con @DriveVIPclubBot\n"
        "💬 Atención directa: {admin}"
    ),
    'ventajas': (
        "🌟 POR QUÉ ELEGIR DRIVEVIPCLUB 🌟\n\n"
        "📊 TRANSPARENCIA TOTAL\n"
        "✅ Planilla detallada: ves videos/fotos de cada modelo\n"
        "✅ Sabes EXACTAMENTE qué recibes antes de pagar\n"
        "✅ Sin sorpresas ni contenido oculto\n\n"
        "📂 ORGANIZACIÓN IMPECABLE\n"
        "✅ Carpetas ordenadas alfabéticamente (A-Z)\n"
        "✅ Encuentra rápido lo que buscas\n"
        "✅ Sin perder tiempo buscando\n\n"
        "💾 SIN LÍMITES\n"
        "✅ Descarga TODO lo que quieras\n"
        "✅ Sin restricciones de cantidad\n"
        "✅ Acceso ilimitado 24/7\n\n"
        "🔄 ACTUALIZACIONES CONSTANTES\n"
        "✅ Material nuevo TODAS LAS SEMANAS\n"
        "✅ Sin costo adicional\n"
        "✅ Siempre hay contenido fresco\n\n"
        "⚡ ACCESO INMEDIATO\n"
        "✅ En 5-15 minutos tienes acceso\n"
        "✅ Pago por MercadoPago (Chile) o PayPal (internacional)\n"
        "✅ Proceso guiado directamente por el bot\n\n"
        "💰 PRECIO ACCESIBLE\n"
        "✅ Desde $4.990 semanal (CLP)\n"
        "✅ Mensual $8.990 CLP ⭐\n"
        "✅ Mensual $10 USD por PayPal 🌍\n"
        "✅ Mejor relación precio/calidad\n\n"
        "🔒 CONFIDENCIALIDAD\n"
        "✅ Tu información 100% segura\n"
        "✅ Acceso directo a tu Gmail\n"
        "✅ Sin contraseñas complicadas\n\n"
        "📊 ESTADÍSTICAS ACTUALIZADAS:\n"
        "• {carpetas} modelos organizadas\n"
        "• {videos} VIDEOS HD\n"
        "• {fotos} fotos\n"
        "• {tamano} de contenido\n"
        "• Actualizaciones semanales garantizadas\n\n"
        "💬 ¿Listo para unirte? /precios\n"
        "📋 Ver contenido: /lista\n"
        "🤖 Ventas: @DriveVIPclubBot\n"
        "🛠️ Ayuda después del pago: {admin}"
    ),
    'auto_00': (
        "🌙 CERRAMOS EL DÍA 🌙\n\n"
        "✅ El Drive sigue disponible 24/7\n"
        "✅ Sin límite de descargas\n\n"
        "💎 Planes: /precios\n"
        "📋 Ver contenido: /lista\n"
        "🤖 Ventas: @DriveVIPclubBot"
    ),
    'auto_08': (
        "☀️ BUENOS DÍAS ☀️\n\n"
        "📦 Seguimos subiendo material NUEVO\n"
        "📋 Revisa /lista para ver qué hay\n"
        "💾 Descarga sin límites\n\n"
        "🤖 Compra y activación: @DriveVIPclubBot\n"
        "💎 Planes: /precios"
    ),
    'auto_12': (
        "🔥 MEDIODÍA 🔥\n\n"
        "🎬 Videos premium en HD\n"
        "📂 Organizados alfabéticamente\n"
        "📊 Planilla transparente: /lista\n\n"
        "🤖 Compra y activación: @DriveVIPclubBot\n"
        "💎 Acceso: /precios"
    ),
    'auto_16': (
        "📦 CONTENIDO DEL DRIVE 📦\n\n"
        "✅ Actualizaciones todas las semanas\n"
        "✅ {carpetas} modelos disponibles\n"
        "✅ {videos} videos • {fotos} fotos\n"
        "✅ {tamano} de contenido\n"
        "✅ 📡 Datos actualizados desde nuestra planilla\n\n"
        "📋 Planilla actualizada: /lista\n"
        "💾 Descarga ilimitada\n"
        "💎 Ver planes: /precios\n"
        "🤖 Compra y activación: @DriveVIPclubBot"
    ),
    'auto_20': (
        "⚡ ACCESO 24/7 ⚡\n\n"
        "📦 Drive siempre disponible\n"
        "💾 Descarga TODO sin límites\n"
        "📊 Transparencia total: /lista\n\n"
        "💳 MercadoPago + PayPal: /precios\n"
        "🤖 Compra y activación: @DriveVIPclubBot"
    ),
}
