services:
  - type: web
    name: DriveVIPclub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8767323818:AAGyw7g6jNrJWqj3_5p2MAVBM1ejfJNIJ4Y
      - key: PUBLIC_GROUP_ID
        value: "-1003902977064"
      - key: VIP_GROUP_ID
        value: "-1004328779223"
      - key: CHANNEL_ID
        value: "-1004398583245"
      - key: ADMIN_USERNAME
        value: "@backadminthree"
      - key: GOOGLE_SHEET_ID
        value: "1jFaDduB_uEKOavf0ZgRrw9zuodyKwHGVDdlLSsH_cVs"
      - key: GOOGLE_SHEET_RANGE
        value: "'Hoja 1'!A:H"
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: ""
      - key: MENSAJES_SHEET_RANGE
        value: Mensajes!A:B
      - key: MP_ACCESS_TOKEN
        value: APP_USR-8269931565190295-071710-0fe418d9bc33e5f5d4ed78badd7a9bd8-3547846805
      - key: DRIVE_FOLDER_ID
        value: "1HxAlgzaZ9acatHGGsVcqcFZXj5Q225vf"
