services:
  - type: web
    name: DriveVIPclub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: PUBLIC_GROUP_ID
        value: "-1003902977064"
      - key: VIP_GROUP_ID
        value: "-1004328779223"
      - key: CHANNEL_ID
        value: "-1004398583245"
      - key: ADMIN_USERNAME
        value: "@backadminthree"
      - key: GOOGLE_SHEET_ID
        value: "1jFaDduB_uEKOavf0ZgRrw9zuodyKwHGVDdlLSsH_cVs"
      - key: GOOGLE_SHEET_RANGE
        value: "'Hoja 1'!A:H"
      - key: MENSAJES_SHEET_RANGE
        value: Mensajes!A:B
      - key: DRIVE_FOLDER_ID
        value: "1EHGYTF0QHiZUFq8FEaa3W3UppGGupaKb"
      - key: LISTADO_SHEET_ID
        value: "1K5lJLdMJfPH76JrV4uC9-QdDly8rLg8XAWxoecWAe3k"
